### ISSUE TITLE
on Chrome the Pasquet article doesn't load

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#88] opened 2021-11-30 04:19 UTC
Hmmm. I got a 404? Checked Safari and that worked though!
<img width="1680" alt="Screen Shot 2021-11-29 at 11 18 35 PM" src="https://user-images.githubusercontent.com/1531144/143984988-d5486202-54a1-4ebe-9bf3-9c7f47876bbe.png">

**Comment by weefuzzy** [comment] 2021-11-30 08:46
This would seem to be the problem
<img width="446" alt="Screenshot 2021-11-30 at 08 44 11" src="https://user-images.githubusercontent.com/27292769/144014221-1a78130c-31b3-4628-b6e1-76ddf361075b.png">
(extra `madewithflucoma /` in the path)

I don't get this on Android Chrome. Was this from following the links at the top of the page?

**Comment by jamesb93** [comment] 2021-12-02 11:36
Knowing how you got to that link will be very helpful. The link is not correct, and I think that some of the programmatic `href=''` that I'm doing is probably not right somewhere and possibly broken in a chrome specific way 🙄 .

Are you able to reproduce this @tedmoore ?

**Comment by jamesb93** [comment] 2021-12-02 11:37
Just FYI I can't reproduce on Chromium 96

**Comment by tedmoore** [comment] 2021-12-06 19:07
Cannot reproduce. Just clicked around for a while to try. I remember that when this did happen for me I tried it twice just to be sure before reporting here...

Maybe we'll just keep our eyes peeled.

**Comment by jamesb93** [comment] 2021-12-08 12:18
Im going to close this to keep the issue free as much as possible.

**Closed by jamesb93** 2021-12-08 12:18 UTC
Labels: bug
